version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules

    command: sleep infinity
    environment:
      - WATCHPACK_POLLING=true

volumes:
  node_modules:
